version: '3'
services:
    apache:
        build: .docker/apache
        container_name: sf4_apache
        ports:
          - 8080:80
        volumes:
          - .docker/config/vhosts:/etc/apache2/sites-enabled
          - ./symfony:/home/wwwroot/sf4
          - ./logs:/var/log/apache2
        depends_on:
          - php
    php:
        build: .docker/php
        container_name: sf4_php
        volumes:
          - ./symfony:/home/wwwroot/sf4
